### ISSUE TITLE
error with implementing arguments

### ISSUE THREAD

**Issue by harishnkr** [ful1e5/clickgen#56]
ctgen: error: unrecognized arguments:  "bitmaps/Bibata... " shown while providing destinantion with the -d argument

**Comment by ful1e5** [comment]
Can you please provide the command, the associated log, and an explanation of the actions being performed? This will aid me in tracing back the source of the issue.

**Comment by harishnkr** [comment]
ctgen build.toml -d "bitmaps/<directory name>" -n '<name>' -c '<comment>'
I installed clickgen via pip and it did not work
I tried reinstalling throught the AUR and it was fixed
Somehow the problem got fixed after trying again from pip.

I'm so sorry I'll provide the error in case it comes up again in the future.

**Comment by ful1e5** [comment]
Closing for now. If an error occurs in the future, please reopen the issue.
